## Credits to John Lieske - https://www.ansible.com/blog/getting-started-writing-your-first-playbook
---
- name: Enable amazon-linux-extras packages
  shell: "amazon-linux-extras enable nginx1.12"

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Update Nginx config
  become: yes
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

- name: Insert Index Page
  template:
    src: files/index.html
    dest: /usr/share/nginx/html/index.html


- name: Restart Nginx
  service: name=nginx state=restarted
